### ISSUE TITLE
No module named 'ReceptiveFieldMaker'

### ISSUE THREAD

**Issue by mishidemudong** [BraintreeLtd/PatchyCapsules#1]
the error is :" from ReceptiveFieldMaker import ReceptiveFieldMaker

   ModuleNotFoundError: No module named 'ReceptiveFieldMaker'  "; 

so, is that file ReceptiveFieldMaker not upload?

**Comment by try-to-anything** [comment]
Excuse me, have you found this document?

**Comment by meltzerpete** [comment]
Hi,

Thanks for your interest in this project. Unfortunately the author of this code has since left our organisation and we cannot provide support. There is a chance the missing module is code borrowed from another Patchy-SAN implementation, for example [this one](https://github.com/seiya-kumada/patchy-san/blob/master/patchy-san/receptive_field_maker.py). Failing that I'm afraid I cannot offer any further help.

Kind regards

**Comment by mishidemudong** [comment]
> Hi,
> 
> Thanks for your interest in this project. Unfortunately the author of this code has since left our organisation and we cannot provide support. There is a chance the missing module is code borrowed from another Patchy-SAN implementation, for example [this one](https://github.com/seiya-kumada/patchy-san/blob/master/patchy-san/receptive_field_maker.py). Failing that I'm afraid I cannot offer any further help.
> 
> Kind regards

thanks for your help, i found this [solution](https://github.com/tvayer/PSCN/blob/3e8037c7f491b483407bbd0c3678e5ae5a98c29a/pscn.py) may be the best .
